sudo: false
language: python
cache: pip
matrix:
  fast_finish: true
  include:
    - python: "2.7"
    - python: "3.4"
    - python: "3.5"
    - python: "3.6-dev"
  allow_failures:
    - python: "3.6-dev"
install:
  - "pip install -r requirements_test.txt"
script:
  - "py.test -v --cov persistent_queue"
after_success:
  - coveralls
